export const GET_COUNTRIES = 'GET_COUNTRIES';
export const GET_COUNTRIES_BY_NAME = 'GET_COUNTRIES_BY_NAME';
export const GET_TOURISTACTIVITY = 'GET_TOURISTACTIVITY';
export const FILTER_COUNTRIES = 'FILTER_COUNTRIES';
export const DETAILS_COUNTRIES = 'DETAILS_COUNTRIES'
export const CREATE_COUNTRIES = 'CREATE_COUNTRIES';
export const CLEAR_DETAIL_COUNTRIES = 'CLEAR_DETAIL_COUNTRIES'

export const ERROR = 'ERROR';

